name: Upload Release Artifacts

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build
      run: |
        GOOS=windows go build -ldflags "-s -w -X main.version=${{github.ref_name}}" -o "ldapswissknife_${{github.ref_name}}_windows_amd64.exe"
        GOOS=darwin go build -ldflags "-s -w -X main.version=${{github.ref_name}}" -o "ldapswissknife_${{github.ref_name}}_macOS_amd64"
        GOOS=linux go build -ldflags "-s -w -X main.version=${{github.ref_name}}" -o "ldapswissknife_${{github.ref_name}}_linux_amd64"

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: Release ${{ github.ref }}
    
    - name: Create zip files
      run: |
        zip ldapswissknife_${{github.ref_name}}_windows_amd64.zip ldapswissknife_${{github.ref_name}}_windows_amd64.exe
        zip ldapswissknife_${{github.ref_name}}_macOS_amd64.zip ldapswissknife_${{github.ref_name}}_macOS_amd64
        zip ldapswissknife_${{github.ref_name}}_linux_amd64.zip ldapswissknife_${{github.ref_name}}_linux_amd64

    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ldapswissknife_${{github.ref_name}}_windows_amd64.zip
          ldapswissknife_${{github.ref_name}}_macOS_amd64.zip
          ldapswissknife_${{github.ref_name}}_linux_amd64.zip